# Generated by Django 4.0.4 on 2022-06-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('ID_admin', models.AutoField(primary_key=True, serialize=False)),
                ('FIO', models.CharField(max_length=50, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирование',
                'db_table': 'admin',
            },
        ),
    ]
