# Generated by Django 4.0.4 on 2022-06-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'ФИО', 'verbose_name_plural': 'ФИО'},
        ),
    ]
