# Generated by Django 4.0.4 on 2022-05-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('ID_Klient', models.AutoField(primary_key=True, serialize=False)),
                ('Phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('Name', models.CharField(max_length=30, verbose_name='Имя')),
                ('Data_rozjden', models.DateField(verbose_name='Дата рождения')),
                ('Skidka', models.CharField(default=0, max_length=3, verbose_name='Скидка')),
                ('Balans', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
            ],
        ),
    ]
