# Generated by Django 4.0.4 on 2022-06-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('ID_Bron', models.AutoField(primary_key=True, serialize=False)),
                ('Data_bron', models.DateTimeField(verbose_name='Дата и время брони')),
                ('Phone_bron', models.CharField(max_length=45, verbose_name='Номер телефона')),
                ('Name_bron', models.CharField(max_length=100, verbose_name='Имя')),
                ('Komment', models.CharField(default=0, max_length=100, null=True, verbose_name='Комментарий')),
                ('Balans', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирование',
                'db_table': 'bron',
            },
        ),
    ]
