# Generated by Django 4.0.4 on 2022-06-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bron',
            name='Balans',
        ),
        migrations.AlterField(
            model_name='bron',
            name='Phone_bron',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
    ]
