# Generated by Django 4.0.4 on 2022-06-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_bron_balans_alter_bron_phone_bron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bron',
            name='Name_bron',
            field=models.CharField(max_length=45, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='bron',
            name='Phone_bron',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
    ]
