# Generated by Django 4.0.4 on 2022-06-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_bron_name_bron_alter_bron_phone_bron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bron',
            name='Komment',
            field=models.CharField(default=0, max_length=100, verbose_name='Комментарий'),
        ),
    ]
