# Generated by Django 4.0.4 on 2022-06-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_bron_komment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bron',
            name='Komment',
            field=models.CharField(default=0, max_length=100, null=True, verbose_name='Комментарий'),
        ),
    ]
