# Generated by Django 4.0.4 on 2022-06-01 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapgrid', '0009_alter_pc_status'),
        ('devices', '0008_bron_pc_id_pc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bron',
            name='PC_ID_PC',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapgrid.pc'),
        ),
    ]
