# Generated by Django 4.0.4 on 2022-06-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_alter_bron_pc_id_pc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bron',
            name='Komment',
            field=models.CharField(blank=True, default=None, max_length=100, verbose_name='Комментарий'),
        ),
    ]
