# Generated by Django 4.0.4 on 2022-06-05 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rate', '__first__'),
        ('shop', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opushen_tovar',
            fields=[
                ('ID_Opushen_tovar', models.AutoField(primary_key=True, serialize=False, verbose_name='ID отпущенных товаров')),
                ('Cen_opushen', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена отпущенных товаров')),
                ('Kol', models.CharField(default=0, max_length=4, verbose_name='Количество')),
                ('Kniga_ucheta_ID_knig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rate.kniga_ucheta')),
                ('Tovar_ID_Tovar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.tovar')),
            ],
            options={
                'verbose_name': 'Книги учета',
                'db_table': 'Opushen_tovar',
            },
        ),
    ]
