# Generated by Django 4.0.4 on 2022-06-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opushen_tovar',
            options={'verbose_name': 'Книга учета', 'verbose_name_plural': 'Книги учета'},
        ),
    ]
