# Generated by Django 4.0.4 on 2022-06-05 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admenu', '0002_alter_admin_options'),
        ('users', '0002_alter_klient_options_alter_klient_phone_and_more'),
        ('mapgrid', '0013_alter_pc_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smen',
            fields=[
                ('ID_Smen', models.AutoField(primary_key=True, serialize=False, verbose_name='ID смены')),
                ('Data_smen', models.DateField(verbose_name='Дата смены')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'db_table': 'smen',
            },
        ),
        migrations.CreateModel(
            name='Kniga_ucheta',
            fields=[
                ('ID_knig', models.AutoField(primary_key=True, serialize=False)),
                ('Nomer_chek', models.IntegerField(verbose_name='Номер чека')),
                ('Operac', models.CharField(max_length=45, verbose_name='Операция')),
                ('Obsh_stoim', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Общая стоимость')),
                ('Data_operac', models.DateTimeField(verbose_name='Дата операции')),
                ('Admin_ID_admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='admenu.admin')),
                ('Klient_ID_Klient', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.klient')),
                ('PC_ID_PC', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapgrid.pc')),
                ('Smen_ID_Smen', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rate.smen')),
            ],
            options={
                'verbose_name': 'Книгв учета',
                'verbose_name_plural': 'Книга учета',
                'db_table': 'kniga_ucheta',
            },
        ),
    ]
