# Generated by Django 4.0.4 on 2022-05-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgrid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='Status',
            field=models.CharField(max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterModelTable(
            name='pc',
            table='pc',
        ),
    ]
