# Generated by Django 4.0.4 on 2022-05-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgrid', '0003_pc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='Status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Свободен'), (2, 'Занят'), (3, 'В обслуживании'), (4, 'Забронирован')], verbose_name='Status'),
        ),
    ]
