# Generated by Django 4.0.4 on 2022-05-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgrid', '0007_alter_pc_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='Status',
            field=models.CharField(choices=[('Free', 'Свободен'), ('NoFree', 'Занят'), ('Repair', 'В обслуживании'), ('Bron', 'Забронирован')], default='Free', max_length=20, verbose_name='Статус'),
        ),
    ]
