# Generated by Django 4.0.4 on 2022-06-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgrid', '0010_alter_pc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='ID_PC',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID ПК'),
        ),
    ]
