# Generated by Django 4.0.4 on 2022-06-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgrid', '0012_alter_pc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='Number',
            field=models.CharField(max_length=3, null=True, unique=True, verbose_name='Номер ПК'),
        ),
    ]
