# Generated by Django 4.0.4 on 2022-06-06 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vid_tovar',
            fields=[
                ('ID_Vid', models.AutoField(primary_key=True, serialize=False, verbose_name='ID товара')),
                ('Vid_Tov', models.CharField(max_length=50, unique=True, verbose_name='Вид товара')),
            ],
            options={
                'verbose_name': 'Вид товара',
                'verbose_name_plural': 'Виды товаров',
                'db_table': 'vid_tovar',
            },
        ),
        migrations.CreateModel(
            name='tovar',
            fields=[
                ('ID_tovar', models.AutoField(primary_key=True, serialize=False, verbose_name='ID товара')),
                ('Photo', models.ImageField(upload_to='../main/static/main/img', verbose_name='Фото')),
                ('Shtrih', models.CharField(max_length=50, unique=True, verbose_name='Штрих-код')),
                ('Nazv_tovar', models.CharField(max_length=50, verbose_name='Название товара')),
                ('Cen_tovar', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена товара')),
                ('Vid_Tovar_ID_Vid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.vid_tovar')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'tovar',
            },
        ),
    ]
