# Generated by Django 4.0.4 on 2022-06-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_tovar_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
