# Generated by Django 4.0.4 on 2022-06-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_tovar_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tovar',
            name='Photo',
        ),
    ]
