# Generated by Django 4.0.4 on 2022-06-03 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapgrid', '0013_alter_pc_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oplat',
            fields=[
                ('ID_Oplat', models.AutoField(primary_key=True, serialize=False)),
                ('Data_opl', models.DateTimeField(verbose_name='Дата и время оплаты')),
                ('Summ_opl', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Сумма оплаты')),
                ('Klient_ID_Klient_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='mapgrid.pc')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'db_table': 'oplat',
            },
        ),
    ]
