# Generated by Django 4.0.4 on 2022-06-03 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oplat',
            old_name='Klient_ID_Klient_id',
            new_name='Klient_ID_Klient',
        ),
    ]
