# Generated by Django 4.0.4 on 2022-06-03 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_klient_options_alter_klient_phone_and_more'),
        ('content', '0002_rename_klient_id_klient_id_oplat_klient_id_klient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oplat',
            name='Klient_ID_Klient',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.klient'),
        ),
    ]
